version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfiles/app.Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app
    environment:
      - APP_ENV=development

  nginx:
    build:
      context: .
      dockerfile: Dockerfiles/nginx.Dockerfile
    ports:
      - "80:80"
    depends_on:
      - app
